--- 
title: "Diario Temtiano edición 27.05.2021"
date: "edición 27.05.2021, difundida inicialmente por temtiteamo"
lang: es-es
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: temtiteamo/diariotemtiano27052021
description: "Mucho texto acerca de un tramo de la historia temtiana."
header-includes:
  - \usepackage{fancyhdr}
  - \usepackage{lipsum}
  - \pagestyle{plain}
  - \fancyhead[CO,CE]{\thepage}
  - \fancyfoot[LE,RO]{\thepage}
---


# Notas de la edición {-}

**Diario Temtiano** edición 27.05.2021

Se espera que la próxima edición, si o si, sea difundida en el o los contextos donde se esté desarrollando la historia temtiana en su mayor parte en el momento de la fecha de su publicación. De la misma forma que esta edición lo fue.

## Novedades en esta edición {-}
- Renombrados los tomos por capítulos. Al estos no ser tan largos, *--capitulo--* encaja mejor con su contenido y dimensión dentro de Diario Temtiano. Lo mismo fue aplicado a lo que antes si eran los capítulos, solo que fueron renombrados por subcapitulos.
- Realizadas modificaciones en la mayoría de los subcapítulos del segundo capitulo: varios títulos fueron adaptados y se agregó texto en muchos de ellos.
- Agregados cuatro subcapítulos nuevos al cuarto capitulo. Estos tratan principalmente sobre: la decaída del dominio temtiano del Club, la categoría Temti que desapareció rápidamente, el renombramiento del Club de Voxxed en el Club de Temti, y la vuelta a la normalidad de este anterior.

## Cambios previstos en la próxima edición {-}
- Continuar poniéndose al día.
- Seguir corrigiendo errores.
- Aplicar lo mismo de la segunda novedad también para el resto de subcapítulos del capitulo tercero.


## Cambios en duda y a evaluar para la próxima edición {-}
- Dividir el cuarto capitulo en dos separados. En el, ocurrió otro antes y después que amerita segmentar la historia temtiana, y no fue tenido en cuenta como tal hasta en esta edición.


